### ISSUE TITLE
Unexpected Application Error! #2

### ISSUE THREAD

**Issue by FallingSnow** [gravitl/netmaker-ui-2#51]
```js
s is null

t@https://[redacted]/assets/index-1ddff8c4.js:832:15556
w5e</cNe</<@https://[redacted]/assets/index-1ddff8c4.js:832:41983
Pb@https://[redacted]/assets/index-1ddff8c4.js:40:24283
nh@https://[redacted]/assets/index-1ddff8c4.js:40:42408
BQ@https://[redacted]/assets/index-1ddff8c4.js:40:41228
nd@https://[redacted]/assets/index-1ddff8c4.js:40:40275
cT@https://[redacted]/assets/index-1ddff8c4.js:40:36885
ku@https://[redacted]/assets/index-1ddff8c4.js:38:3279
oa/<@https://[redacted]/assets/index-1ddff8c4.js:40:34263
```

I cannot track this one down, but it does happen when I click on a graph, then the network tab.

I suggest shipping source-maps in your production builds so these errors can be tracked down more effectively.

**Comment by Aceix** [comment]
There was a common underlying issue which led to this bug in various network pages. It has been resolved in #46

**Comment by FallingSnow** [comment]
Still occuring on v0.20.4
```js
Unexpected Application Error!
s is null

t@https://dashboard.netmaker.[redacted]/assets/index-8e1c8510.js:879:15571
rIe</<@https://dashboard.netmaker.[redacted]/assets/index-8e1c8510.js:879:41998
Yb@https://dashboard.netmaker.[redacted]/assets/index-8e1c8510.js:40:24270
mh@https://dashboard.netmaker.[redacted]/assets/index-8e1c8510.js:40:42395
GX@https://dashboard.netmaker.[redacted]/assets/index-8e1c8510.js:40:41215
rd@https://dashboard.netmaker.[redacted]/assets/index-8e1c8510.js:40:40262
JR@https://dashboard.netmaker.[redacted]/assets/index-8e1c8510.js:40:36872
ku@https://dashboard.netmaker.[redacted]/assets/index-8e1c8510.js:38:3279
ua/<@https://dashboard.netmaker.[redacted]/assets/index-8e1c8510.js:40:34250
```

I still recommend shipping with source maps until the UI becomes more reliable...

**Comment by FallingSnow** [comment]
Glad to see you guys are shipping source maps now *thank you*! Here is the error with source maps.
```js
TypeError: s is null
    t sigma.js:177
    pIe react-sigma_core.esm.min.js:1
    React 10
    a useState.js:24
    S useMergedState.js:59
    n useEvent.js:10
    he Tabs.js:132
    onClick index.js:269
    C TabNode.js:29
    onClick TabNode.js:57
    React 16
    <anonymous> main.tsx:10
```

It seems this may be due to WebGL being disabled on my browser (due to my privacy settings). I suppose that would make it a low priority since I assume not many have WebGL disabled. 

...would be a nice to have a prettier error though.

**Comment by Aceix** [comment]
@FallingSnow so the graph page does not open at all for you right?

**Comment by Aceix** [comment]
> Glad to see you guys are shipping source maps now _thank you_! Here is the error with source maps.
> 
> ```js
> TypeError: s is null
>     t sigma.js:177
>     pIe react-sigma_core.esm.min.js:1
>     React 10
>     a useState.js:24
>     S useMergedState.js:59
>     n useEvent.js:10
>     he Tabs.js:132
>     onClick index.js:269
>     C TabNode.js:29
>     onClick TabNode.js:57
>     React 16
>     <anonymous> main.tsx:10
> ```
> 
> It seems this may be due to WebGL being disabled on my browser (due to my privacy settings). I suppose that would make it a low priority since I assume not many have WebGL disabled.
> 
> ...would be a nice to have a prettier error though.
> 
> Edit: Also, nice job on the new pretty error screen.

I have confirmed WebGL is required, and the page does not show in this scenario.
Currently, we don't supporting SVG-based graphs. We may extend support later scince majority of users have WebGL enabled browsers

**Comment by FallingSnow** [comment]
> @FallingSnow so the graph page does not open at all for you right?

The whole window is replaced with an application error message.
